services:
  db-archcontrol:
    image: postgres:15-alpine
    container_name: archcontrol-db
    restart: always
    # Docker leerá automáticamente el archivo .env en la misma carpeta
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432" # Expone el puerto (ej. 5432) hacia tu máquina local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - archcontrol_db_data:/var/lib/postgresql/data

volumes:
  archcontrol_db_data: # Esto asegura que tus datos no se borren al apagar Docker